### ISSUE TITLE
Could not find :ScanditCaptureCore

### ISSUE THREAD

**Issue by Yousaf128** [Scandit/datacapture-android-samples#8] opened 2022-04-25 08:51 UTC
When i have run the app facing this issue

Could not find :ScanditCaptureCore:.
Required by:
    project :VINCodesSample..
    
    Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':VINCodesSample:debugRuntimeClasspath'.

**Comment by ScanditSupport** [comment] 2022-04-25 10:06
Hi @Yousaf128,

Please accept my apologies for the inconvenience, the issue is caused by an error and the samples need to be adjusted, as currently, they rely on local dependencies:
https://github.com/Scandit/datacapture-android-samples/blob/master/BarcodeCaptureSimpleSample/build.gradle#L34-L36

This will be fixed soon, in the meantime you can either:

- Set up the mavenCentral dependencies: https://docs.scandit.com/data-capture-sdk/android/add-sdk.html#add-the-sdk
- Or download the SDK bundle from your Scandit dashbard, which includes the libraries: https://ssl.scandit.com/sdk/download/scandit-datacapture-android-6.12.1.zip 

In case you have more detailed questions, please feel free to reach out to us directly: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Closed by ScanditSupport** 2022-04-25 10:06 UTC
